### ISSUE TITLE
JSON lint tab error

### ISSUE THREAD

**Issue by muratabur** [SuadeLabs/fire-validator#1]
- pasting LOAN schema into fire-validator gives some JSON lint errors citing tabs used instead of spaces.
- but no errors appear on jsonlint.com
- is validator being too strict with whitespace?

**Comment by gobbledygook88** [comment]
Yes, we should not be worrying about whitespace in the linter. No need to be so strict.
On a related note, we use the linter provided by [jslint.com](http://jslint.com) since it detects duplicate object keys.
